const PIPELINE_CONFIG = {
    REFETCH_ABUSE_IP_WITH_INFO_AFTER_IN_HOURS: 6,
    DB_ABUSE_IP_WITH_INFO_EXPIRATION: 8 * 24 * 60 * 60, // 8 days in seconds
    CHUCK_SIZE: 100,
    NUMBER_OF_ITERATIONS_PER_REQUEST: 10,
    SLEEP_BETWEEN_REQUESTS_IN_MS: 5000,
};
export default PIPELINE_CONFIG;
