const PIPELINE_CONFIG = {
    DB_ABUSE_IP_WITH_INFO_EXPIRATION: 3 * 24 * 60 * 60, // 3 days in seconds
    REFETCH_ABUSE_IP_WITH_INFO_AFTER_IN_HOURS: 6,
    CHUCK_SIZE: 100,
    NUMBER_OF_ITERATIONS_PER_REQUEST: 7,
    SLEEP_BETWEEN_REQUESTS_IN_MS: 5000,
};
export default PIPELINE_CONFIG;
